suppressPackageStartupMessages(library(haven))
suppressPackageStartupMessages(library(dplyr))
source("C:/Users/jconkle/Documents/GitHub/OSE-DA-NT/analysis_datasets/02_codes/1_layer2_utils.r")

disagg_map <- read_disagg_map()
src <- haven::read_dta(file.path(cmrs_input_dir, "CMRS_IYCF.dta"))
out <- build_layer2_dataset(src, disagg_map, dataset_name = "CMRS_IYCF.dta") %>% mutate(across(everything(), as.character))

cols <- c("SEX","AGE","RESIDENCE","WEALTH","EDUCATION","HEAD_OF_HOUSEHOLD","MOTHER_AGE","DELIVERY_ASSISTANCE","PLACE_OF_DELIVERY","DELIVERY_MODE","MULTIPLE_BIRTH","REGION")
full_t <- out %>% filter(if_all(all_of(cols), ~ .x == "_T"))
cat("rows=", nrow(out), "\n", sep="")
cat("fully_t=", nrow(full_t), "\n", sep="")
print(full_t %>% count(BackgroundCharacteristics, sort=TRUE), n=80)
print(full_t %>% count(BackgroundCharacteristics, StandardDisaggregations, sort=TRUE) %>% head(120), n=120)
non_nat <- full_t %>% filter(!(BackgroundCharacteristics %in% c("National", NA_character_) | trimws(coalesce(BackgroundCharacteristics,"")) == ""))
cat("non_national_fully_t=", nrow(non_nat), "\n", sep="")
