Set-Location "C:/Users/jconkle/Documents/GitHub/OSE-DA-NT"
Rscript "analytical_database/per_dataset/1_build_cmrs2_series_ane.r"
Rscript "analytical_database/per_dataset/2_build_cmrs2_bw.r"
Get-ChildItem "C:/Users/jconkle/UNICEF/Data and Analytics Nutrition - Analysis Space/github/analysis_database/cmrs2_series_ane.parquet"
Get-ChildItem "C:/Users/jconkle/UNICEF/Data and Analytics Nutrition - Analysis Space/github/analysis_database/cmrs2_bw.parquet"
